/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScenarioDto : The scenario data transfer object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScenarioDto {
    #[serde(rename = "customers")]
    pub customers: Vec<models::CustomerDto>,
    #[serde(rename = "endTime")]
    pub end_time: Option<String>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "startTime")]
    pub start_time: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "vehicles")]
    pub vehicles: Vec<models::StandardMagentaVehicleDto>,
}

impl ScenarioDto {
    /// The scenario data transfer object
    pub fn new(
        customers: Vec<models::CustomerDto>,
        end_time: Option<String>,
        id: uuid::Uuid,
        start_time: Option<String>,
        status: String,
        vehicles: Vec<models::StandardMagentaVehicleDto>,
    ) -> ScenarioDto {
        ScenarioDto {
            customers,
            end_time,
            id,
            start_time,
            status,
            vehicles,
        }
    }
}
