/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScenarioMetadataDto : The scenario metadata data transfer object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScenarioMetadataDto {
    #[serde(rename = "endTime")]
    pub end_time: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "startTime")]
    pub start_time: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "vehicleData", skip_serializing_if = "Option::is_none")]
    pub vehicle_data: Option<Vec<models::VehicleDataDto>>,
}

impl ScenarioMetadataDto {
    /// The scenario metadata data transfer object
    pub fn new(end_time: String, id: uuid::Uuid, start_time: String, status: String) -> ScenarioMetadataDto {
        ScenarioMetadataDto {
            end_time,
            id,
            start_time,
            status,
            vehicle_data: None,
        }
    }
}

