/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StandardMagentaVehicleDto : The vehicle data transfer object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StandardMagentaVehicleDto {
    #[serde(rename = "activeTime")]
    pub active_time: Option<f64>,
    #[serde(rename = "coordX")]
    pub coord_x: f64,
    #[serde(rename = "coordY")]
    pub coord_y: f64,
    #[serde(rename = "customerId")]
    pub customer_id: Option<uuid::Uuid>,
    #[serde(rename = "distanceTravelled")]
    pub distance_travelled: Option<f64>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "isAvailable")]
    pub is_available: bool,
    #[serde(rename = "numberOfTrips")]
    pub number_of_trips: Option<u32>,
    #[serde(rename = "remainingTravelTime")]
    pub remaining_travel_time: Option<f64>,
    #[serde(rename = "vehicleSpeed")]
    pub vehicle_speed: Option<f64>,
}

impl StandardMagentaVehicleDto {
    /// The vehicle data transfer object
    pub fn new(
        active_time: Option<f64>,
        coord_x: f64,
        coord_y: f64,
        customer_id: Option<uuid::Uuid>,
        distance_travelled: Option<f64>,
        id: uuid::Uuid,
        is_available: bool,
        number_of_trips: Option<u32>,
        remaining_travel_time: Option<f64>,
        vehicle_speed: Option<f64>,
    ) -> StandardMagentaVehicleDto {
        StandardMagentaVehicleDto {
            active_time,
            coord_x,
            coord_y,
            customer_id,
            distance_travelled,
            id,
            is_available,
            number_of_trips,
            remaining_travel_time,
            vehicle_speed,
        }
    }
}
